#! /bin/sh


# Define workspaces
ws1="terminal"
ws2="internet"
ws3="programming"
ws4="music"

sxhkd &

# Configurate BSPWM
#-----------------------------------------------------------
bspc config border_width 	4
bspc config window_gap 		0
bspc config top_padding 	0
bspc config bottom_padding	-10


bspc config pointer_follows_focuse false
bspc config focus_by_distance true
bspc config focused_border_color 		"#404040"
bspc config focuses_locked_border_color

bspc config split_ratio          0.50

bspc config gapless_monocle 	true
bspc config borderless_monocle 	true
bspc config leaf_monocle 	true
bspc config adaptative_raise 	true
#-----------------------------------------------------------

# Change background
feh --bg-fill  ~/src/hexakis/wallpaper/shrine.png

# Set workspaces
bspc monitor -d $ws1 $ws2 $ws3 $ws4

# Program rules
bspc rule -a IceCat desktop='^2'

# Start custom Polybar config
polybar debuggingisfun
